### ISSUE TITLE
Multiple definitions of structure Direction in little_field_gather.c and little_D.c

### ISSUE THREAD

**Issue by sunpho84** [etmc/tmLQCD#485]
```
/usr/bin/ld: ./lib/libxchange.a(little_field_gather.o):/home/francesco/QCD/SORGENTI/tmLQCD/build_quda/xchange/../../xchange/little_field_gather.c:47: multiple definition of `Direction'; ./lib/libhmc.a(little_D.o):/home/francesco/QCD/SORGENTI/tmLQCD/build_quda/../little_D.c:71: first defined here
```

a `Direction` structure is indeed defined in both `little_field_gather.c` and `little_D.c`, but in the second is never referred, so I guess it can be removed

**Comment by urbach** [comment]
are you sure that this is the latest version of the DD solver? I have the feeling that I fixed these problems already at some point?

> 
> ```
> /usr/bin/ld: ./lib/libxchange.a(little_field_gather.o):/home/francesco/QCD/SORGENTI/tmLQCD/build_quda/xchange/../../xchange/little_field_gather.c:47: multiple definition of `Direction'; ./lib/libhmc.a(little_D.o):/home/francesco/QCD/SORGENTI/tmLQCD/build_quda/../little_D.c:71: first defined here
> ```
> 
> a `Direction` structure is indeed defined in both `little_field_gather.c` and `little_D.c`, but in the second is never referred, so I guess it can be removed
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/etmc/tmLQCD/issues/485

-- 
Carsten Urbach
e-mail: ***@***.***
        ***@***.***
Fon   : +49 (0)228 73 2379
skype : carsten.urbach
URL: http://www.carsten-urbach.eu

**Comment by kostrzewa** [comment]
This may very well be. https://github.com/etmc/tmLQCD/pull/460 has been waiting for a review since April 2019 and there are conflicts in various files indicated in that pull.

**Comment by kostrzewa** [comment]
I think we need to merge master into quda_work first and then see from there... I'm afraid the number of conflicts is really high.

**Comment by kostrzewa** [comment]
@urbach the multiple definitions stuff definitely is still a problem in the master branch, it's just "by accident" that the issue was not triggered by compilers prior to GCC 10 apparently...
